remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - docs/Architecture.md
  - docs/WritingPlugins.md
  - docs/License.md
title: Malaria
description: An MQTT System Statistics Reporter
